### ISSUE TITLE
`SliderConstraint.GetCurrentPosition()` not a function.

### ISSUE THREAD

**Issue by KyroVibe** [jrouwe/JoltPhysics.js#128]
After creating a `SliderConstraint`, I'm unable to use the `GetCurrentPosition()` function. Here is the gist of what I'm doing in my project:
```typescript
const constraint = sliderConstraintSettings.Create(bodyA, bodyB);
        
this._constraints.push(constraint);
this._joltPhysSystem.AddConstraint(constraint);
        
console.debug(`Slider Position: ${(constraint as Jolt.SliderConstraint).GetCurrentPosition()}`);
```
And here is the following error:
![image](https://github.com/jrouwe/JoltPhysics.js/assets/20159878/c1e3ad1b-16e9-4187-bd72-93d4b7329ebd)

I've tried calling `GetCurrentPosition()` before adding it to the system, after, and after running a time step. Each case produces the same issue. Outside of calling the function, Slider Constraints behave as expected.

**Comment by jrouwe** [comment]
I'm not sure if `as` works for C++ classes, I use `Jolt.castObject(constraint, Jolt.SliderConstraint)`

**Comment by KyroVibe** [comment]
Thanks a ton, you were right. Works perfect now!
