### ISSUE TITLE
Add BodyInterface::CreateBodyWithID and Quat::operator*

### ISSUE THREAD

**Issue by Kazey974** [jrouwe/JoltPhysics.js#185]
Hello,
I need CreateBodyWithID to be able to sync my server with my clients :

```
interface BodyInterface {
	Body CreateBodyWithID([Const, Ref] BodyID inBodyID, BodyCreationSettings inSettings);
}
```

Also Quat.Mul(Vec3) to rotate a Vec3 would be useful.

**Comment by jrouwe** [comment]
I've added CreateBodyWith ID in abec58411cd4c840ed82ffc119e04b5e7586da37 (do you build your own version or do you need a release?)

W.r.t. Quat.Mul: Unfortunately webidl only exposes the [=, +=, -=, *=](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#operators) operators. I haven't yet found a way to expose the `*` operator in JS.

**Comment by Kazey974** [comment]
Thanks a lot, I will try building it, doesn't sound too complicated.

**Comment by RobvandenBerg** [comment]
@jrouwe To properly sync clients, I believe sending a BodyID's indexAndSequenceNumber over the network, and then using CreateBodyWithID is the recommended approach. Is there a way to construct a BodyID in the release version from an indexAndSequenceNumber that can be passed on to CreateBodyWithID? I've tried looking through JoltJS.idl for an exposed BodyID creation method but could not find a way to do it.

**Comment by jrouwe** [comment]
I've created a PR in emscripten that allows me to expose `Quat::operator *`: https://github.com/emscripten-core/emscripten/pull/22770. Let's hope they accept it.
