### ISSUE TITLE
AdjustCenterOfMass shifts the local frame of the children shapes

### ISSUE THREAD

**Issue by LeXXik** [jrouwe/JoltPhysics.js#194]
Calling `AdjustCenterOfMass` shifts the local position of the mutable compound children.

Clip: static mutable shape getting added a box shape child and called `AdjustCenterOfMass`:

https://github.com/user-attachments/assets/3321b683-f831-445f-b74c-0a81a9363f33

**Comment by jrouwe** [comment]
Are you notifying the body interface that the shape changed? See:

https://github.com/jrouwe/JoltPhysics/blob/c7d9114f44d98cb76ecf3806dc3621cd73371226/Samples/Tests/Shapes/MutableCompoundShapeTest.cpp#L105-L110

**Comment by LeXXik** [comment]
I did not! That was the issue. Thank you!
