### ISSUE TITLE
Publish packages to npm

### ISSUE THREAD

**Issue by isaac-mason** [jrouwe/JoltPhysics.js#2]
Hi!

First off - this is such an exciting project!

In order to make consumption of the library easier, it would be great to publish the library to npm.

As for how this could look, another physics library with js bindings, [Rapier, publishes two packages to npm](https://rapier.rs/docs/user_guides/javascript/getting_started_js#installing-rapier-from-npm):
- a package with a separate WASM file, usable with bundlers that can handle wasm files - `@dimforge/rapier3d` (like `Examples/js/jolt.wasm.js` + `Examples/js/jolt.wasm.wasm`)
- a package with the WASM inlined encoded as base64, for compatibility with more bundlers + use of the library without a bundler - `@dimforge/rapier3d-compat` - (like `Examples/js/jolt.js`)

The same approach could be used here?

I'm very happy to help with this.

**Comment by isaac-mason** [comment]
For some extra context on my use case:

I and some others in the [Poimandres](https://github.com/pmndrs) community are keen to start using Jolt Physics in game-dev web projects.

The folks at Poimandres maintain a library called [@react-three/fiber](https://github.com/pmndrs/react-three-fiber), which simplifies creating 3d experiences with React and three.js. We've created wrappers for physics libraries before, such as ([@react-three/cannon](https://github.com/pmndrs/use-cannon) and [@react-three/rapier](https://github.com/pmndrs/react-three-rapier)). There's interest in doing the same for Jolt, especially given its leaning toward game-development use cases.

**Comment by jrouwe** [comment]
Hello,

I agree that it would be great to publish Jolt as a npm package, problem is that I'm a C++ coder and I know very little about the whole JavaScript community and the eco system around it. So if you want to help out and make it easier for people to integrate the library then your help is very welcome!

W.r.t. the actual packages: Is there also interest in having a debug version of the library as a package? I've noticed that when you do something wrong in JavaScript and call a C++ function the browser just throws a very cryptic error message that tells me nothing unless I build a debug version and I see the actual C++ code that triggered e.g. an assert.

**Comment by isaac-mason** [comment]
A debug version could be useful, for sure! And +1 to what @krispya said, we have plenty to learn in this space.

I'll find some time soon to make a PR for what we've discussed above (publishing to npm, debug build, etc)
