### ISSUE TITLE
[Feature request] expose the APIs about  CharacterVirtual  & more APIs about Body

### ISSUE THREAD

**Issue by finscn** [jrouwe/JoltPhysics.js#20]
Related discussion: 
 the APIs about  CharacterVirtual 
https://github.com/jrouwe/JoltPhysics.js/discussions/19

more APIs about Body 
https://github.com/jrouwe/JoltPhysics.js/discussions/18

**Comment by jrouwe** [comment]
I exposed both in 3e3e7702dd26a1bd8b9d0ea651dda9d0a4b6a3a0

to get a body use ```physicsSystem.GetBodyLockInterface().TryGetBody(body_id)```

for the ```CharacterVirtual``` take a look at the C++ examples (it's the same interface, I didn't create a demo for it in JS yet)
