### ISSUE TITLE
Body Creation/Destruction Bulk Methods

### ISSUE THREAD

**Issue by Ctrlmonster** [jrouwe/JoltPhysics.js#215]
Hello!

First off, thanks for making such a great open source library and letting us JS folks partake in the fun :)

I've been working on a stress-test demo for the multi-threaded wasm version. I've seen in the docs that it's recommended to use the bulk methods (i.e. `BodyInterface.AddBodiesFinalize`, `BodyInterface.RemoveBodies`, etc.), but I've not seen them on the `BodyInterface` in the JS version. Am I missing something or are they currently not exposed?

In case of the latter, how often should one call `PhysicsSystem.OptimizeBroadPhase`, if for example,  bodies get spawned every frame?
Cheers

**Comment by jrouwe** [comment]
> Am I missing something or are they currently not exposed?

They are indeed not exposed. I'll see if that can be done.

> In case of the latter, how often should one call PhysicsSystem.OptimizeBroadPhase, if for example, bodies get spawned every frame?

I wrote something about that in the documentation: https://jrouwe.github.io/JoltPhysics/class_physics_system.html#ab3cd9f2562f0f051c032b3bc298d9604

Let me know if that helps.

**Comment by jrouwe** [comment]
Ok, that was not too difficult. I don't have time to make a release though, so you'll have to compile from source or temporarily use the one that is compiled with the demos: https://jrouwe.github.io/JoltPhysics.js/js/jolt-physics.multithread.wasm-compat.js

**Comment by Ctrlmonster** [comment]
Oh wow that was fast indeed haha

Thanks, I'll give the demo version a try (and thanks for the docs pointer, I missed that section). 

Have a great weekend! 

(thought I'd leave a screenshot – this is Jolt running 2000 active bodies at stable 60 on a 7 year old Thinkpad!!)
![laptop](https://github.com/user-attachments/assets/5d9af35c-bd53-4a32-9893-c79c0aa14857)

**Comment by jrouwe** [comment]
In a few moments 0.29.0 will be published that includes these changes.
