### ISSUE TITLE
State Recorder - Inconsistent Deterministic 2D Funnel

### ISSUE THREAD

**Issue by PhoenixIllusion** [jrouwe/JoltPhysics.js#22]
Use case:
* Exposing storing of StateRecorder (currently using exposed StateRecorderImpl)

Test Case:
* 2D Funnel initialized with lower gravity
* Physics Engine fixed to run at Step(0.05, 1)
* Every second a StateRecorderImpl saved - 0, 1, 2, 3sec
* Re-running the saved state from each timestamp, from 0 seconds, 1 second, etc
* Wait at end of each run for 10-20 seconds to 'settle'
* Screenshot-ing final sphere collection for each test case from exact same camera configuration

Expected Result
* Screenshot comparison should resolve to same exact same ball configuration each run, pixel comparison-wise

Actual Result:
* Each test case approximates same ball configuration, but not 100% the same when image-diffed using GIMP 'difference' between layers

Fork:
https://github.com/PhoenixIllusion/JoltPhysics.js/tree/feature/state-recorder

Sample Plunkr:
https://plnkr.co/plunk/spvDTIaaDw0jOVD0

Even running from the same StateRecording over and over [ex: run multiple times from 0 sec] appears to have very slightly different screenshots at the end.

This may be due to my misunderstanding exactly of how to force the physics engine to fully reset its state and how to force it to run the engine step-by-step exactly the same way every time to achieve Determinism. I'd assumed if the engine only ran Step(0.05, 1) every single run it would always reach the same conclusions.

My end goal is to setup a 20-30 unit ring-buffer of StateRecorders, saving at a 5fps FPS of physics, to record the last X seconds of physics for rollback support in netcode.

![2023-09-29-run-000](https://github.com/jrouwe/JoltPhysics.js/assets/756488/3b8eb05e-92ab-4f64-8428-c177bb8c41fa)
![2023-09-29-run-001](https://github.com/jrouwe/JoltPhysics.js/assets/756488/e8bcb548-17de-4ca7-b71e-0b65e7ced734)
![2023-09-29-run-002](https://github.com/jrouwe/JoltPhysics.js/assets/756488/2d7ae4c1-0ace-4367-9e06-6258d2bdb31e)

**Comment by jrouwe** [comment]
Hello,

I think the issue is that it takes a VERY long time for the simulation to settle and the bodies to go to sleep. Until that time they're moving almost imperceptibly so when you take screenshots at different times you'll see different results.

I changed the code like this:

```
function renderExample() {
        ...
	let all_sleeping = true;
	for (let i = 0, il = dynamicObjects.length; i < il; i++) {
                ...
		if (body.IsActive())
			all_sleeping = false;
	}

	console.log("all sleeping: " + all_sleeping);
```

When I then observe the console and wait until it traces ```all sleeping: true``` (which on my machine takes nearly 3.4k frames) and then make a screenshot, I don't see a difference anymore.

**Comment by PhoenixIllusion** [comment]
Thank you. I confirmed the same behavior. After the first 5 recordings, I increased the physics loop execution/time-rate 100x. After the several thousand accelerated physics-frames, I confirmed the same settled positions. All my StateRecorder now resolve the exact same configuration, pixel-perfect.

I will check into some better test cases of SaveState/RestoreState and see if I can make a worthwhile Example for general public usage.

**Comment by PhoenixIllusion** [comment]
Disabled the physics loop in `example.js`, and ran the entire physics simulation at 60fps, recording 5 fps snapshots of StateRecorder the entire simulation (100 total recorder instances). Snapped back to seconds 0, 1, 2 and re-ran it, and on hitting one of my previous snapshot frames used 'IsEqual' to test the State as being the same. All 100 recorded states re-validated on every subsequent simulation run, from every saved snapshots.

Re-using a StateRecorderImpl requires that StateRecorderImpl implements a 'void Clear()' method. Just rewinding and re-recording over the state will fail with `Failed to properly recover state, different stream length!` error:

```
void StateRecorderImpl::Clear() {
	mStream.clear();
	mStream.str ("");
}
```
