### ISSUE TITLE
Issues in Character Virtual test

### ISSUE THREAD

**Issue by jrouwe** [jrouwe/JoltPhysics.js#25]
From #24, the Character Virtual test has some issues that need to be fixed:

Hitting some objects too hard results in some weird physics, kicking the user or the object away. Possibly because the user is set to be very heavy.

The default example.js of tying the physics engine to the requestAnimationFrame causes weird things if you background the tab and foreground, causing the physics force to build over time and snap the user out of the world all at once. Get on the conveyor belt or start jumping, background the tab, wait, foreground and get a snap up or sideways.

**Comment by jrouwe** [comment]
Fixed in 6e41ceed82edd8a9b9136c9da1d0c4a9a3f52023

**Comment by LeXXik** [comment]
About the changing windows tab - the issue here is that delta time passed by rAF becomes too large. We usually clamp it, so it doesn't become unreasonable. If the simulation is supposed to run at 1/60, then that would be a good max value.

**Comment by jrouwe** [comment]
You can set the max to 1/30 or even 1/15 for example as long as during the update you then increase the number of steps so that each step is roughly 1/60th (so 1/60 = 1 step, 1/30 = 2 steps, 1/15 = 4 steps). Note that it is possible to run the simulation at a lower frequency and it will really depend on your scene if the simulation will be stable or not, if you run at 1/30 with 1 simulation step for example, all constraints will be much softer and there's a bigger chance of objects 'tunneling' through other objects.
