### ISSUE TITLE
[Feature] Add an argument to build.sh for setting which branch of JoltPhysics to use

### ISSUE THREAD

**Issue by finscn** [jrouwe/JoltPhysics.js#26]
Current build.sh has used  GIT_TAG="4d02303b7002cb9692d17828b1c685451a7c6ebc" of JoltPhysics .

If I want to use the last version of master branch  of JoltPhysics , I have to change CMakeLists.txt

I hope I could do that with an agrument. like this: 
```
./build.sh -b master
or 
./build.sh -t 4d02303b7002cb9692d17828b1c685451a7c6ebc 
```

**Comment by jrouwe** [comment]
I don't really see what the value of that option is? The version that is in that file is the latest version that is tested to work (and I just updated it an hour ago). Updating the version won't give you any new functionality, Jolt.idl needs to be updated for that.
