### ISSUE TITLE
Generate TypeScript definitions as part of build

### ISSUE THREAD

**Issue by isaac-mason** [jrouwe/JoltPhysics.js#3]
Hi!

This issue is closely related to another I opened for publishing packages to npm: https://github.com/jrouwe/JoltPhysics.js/issues/2

Is there any interest in generating [typescript](https://www.typescriptlang.org/) type definitions as part of this repo?

Adding typescript type definitions would not only open this library up to typescript projects, it would also improve the javascript development experience, e.g. IDEs can use the type information to provide better IntelliSense.

---

As far as I know, there's no obvious choice of tool when generating typescript definitions for emscripten projects.

There's a repo called [ammojs-typed](https://github.com/giniedp/ammojs-typed), which provides typescript definitions for ammojs. The author created a tool called [webidlt2ts](https://github.com/giniedp/webidl2ts) to auto-generate types from webidl2 files.

Using a very minorly modified version of webidl2ts, I was able to generate types from `JoltJS.idl`. I didn't need to modify `JoltJS.idl` at all. The `webidl2ts` package just needed a typescript version update, plus some extra support for handling an extra collection type seen here but not in ammojs.

My fork of webidl2ts is here: https://github.com/isaac-mason/webidl2ts/tree/chore-update-typescript

Keen to hear if there are other better choices out there too.

---

Let me know if you have any interest in this being part of the core repository.

Alternatively, types could be submitted to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), or could be their own project like `ammojs-typed` if you're not keen to handle this in this repo.

--- 

If there is interest, I'm very happy to help with implementation 🙂

**Comment by isaac-mason** [comment]
For reference, here's a typescript definition file I generated using my forked webidl2ts:

[JoltJS.d.ts](https://github.com/jrouwe/JoltPhysics.js/files/10011233/JoltJS.d.ts.txt)

**Comment by jrouwe** [comment]
Hello,

Again, I'm very open to help! If it makes it easier for developers if there is a typescript definition file available then I'm happy for that to be part of the repository. If possible it would be nice if your changes to webidl2ts are merged back to the main version so that we can use the vanilla version, but that obviously depends on its author.

**Comment by isaac-mason** [comment]
Great! 🙂 

As a first step then, I'll create a PR on the original repo and try to reach out to the author.

We'll see if the original author is happy to incorporate the changes and continue maintaining. I have noted however the repo hasn't been updated in 2 years, and there's an open PR on the repo that hasn't been actioned.

If I can't get any traction there, we can explore other avenues, e.g. myself or pmndrs hosting a maintained fork, or something like this.

**Comment by isaac-mason** [comment]
I've made a PR over at giniedp/webidl2ts now: https://github.com/giniedp/webidl2ts/pull/14

The typescript version upgrade wasn't needed in the end, hopefully makes the PR a little more palatable 🙁

**Comment by isaac-mason** [comment]
I haven't gotten any traction on that PR just yet - I'll look into maintaining a fork of webidl2ts either myself or with pmndrs.

**Comment by jrouwe** [comment]
Agreed, too bad the author isn't responding.

**Comment by jrouwe** [comment]
Note that there are already a couple of other active forks if you look at the network graph: https://github.com/giniedp/webidl2ts/network

These two seem to be the most active:

* https://github.com/Milkshake-Inc/webidl2ts (very recent commits)
* https://github.com/toji/webidl2ts (multiple authors committing)
 
But I'll leave it to you to decide.

**Comment by isaac-mason** [comment]
I hadn't seen into those, thanks! I'll take a look

**Comment by isaac-mason** [comment]
In the end, I opted to create a fork under pmndrs: https://github.com/pmndrs/webidl-dts-gen

I've made some improvements and incorporated some changes in other forks (see: https://github.com/pmndrs/webidl-dts-gen/blob/main/packages/webidl-dts-gen/CHANGELOG.md)

I'll do some more testing/bikeshedding before making a PR here. Hoping to have some time to push this & the npm publishing issue over soon 🙂
