### ISSUE TITLE
Cannot find EAllowedDOFs::All 

### ISSUE THREAD

**Issue by LeXXik** [jrouwe/JoltPhysics.js#48]
Hmm, I can't seem to find a corresponding `All` of EAllowedDOFs enum. Is it not exposed? I tried to use `Jolt.All`, but it seems to be something else. <s>Should I use number 1 to represent it?</s>

**Comment by jrouwe** [comment]
Yes this is missing indeed. Emscripten doesn't properly scope enums and the name All was already taken. I have since writing this figured out a way to deal with this so I will create a fix. In the meantime you can use the integer 31.

**Comment by LeXXik** [comment]
Hmm, setting it to 31, give give me some strange results:

https://github.com/jrouwe/JoltPhysics.js/assets/5677782/c747055e-966d-4bfa-a9c7-6cc1cfbdf591

I will better wait for your fix and skip this option for now.

**Comment by jrouwe** [comment]
v0.7.0 has the new enum value. Please note this is a breaking change, see: https://github.com/jrouwe/JoltPhysics.js/releases/tag/0.7.0

**Comment by LeXXik** [comment]
You are awesome, thank you! Since the lib is still in sub 1.0.0, I don't mind breaking changes. In fact I welcome them, as this is the best time to introduce those.
