### ISSUE TITLE
Changing motion type

### ISSUE THREAD

**Issue by LeXXik** [jrouwe/JoltPhysics.js#57]
I am trying to change the motion type of an active body from dynamic to kinematic. However it doesn't seem to affect the body, as it continues to move as dynamic. Perhaps I misunderstand the body types in Jolt? I am assuming the dynamic one will be moved by simulation, while kinematic one will be moved by user.

I tried both variants, and they seem to be identical:
```js
bodyInterface.SetMotionType(body.GetID(), type, Jolt.Activate);
body.SetMotionType(type);
```

Here are 2 sim steps log of a dynamic body in empty space, right after it was changed to EMotionType_Kinematic type (int 1). Even though it is kinematic, it still keeps falling due to gravity:

![image](https://github.com/jrouwe/JoltPhysics.js/assets/5677782/001ac233-c673-4022-a51b-b568eb93fd66)

This doesn't happen when I switch to static. Maybe I misunderstand the types.

**Comment by jrouwe** [comment]
If you make a body kinematic, it continues with the velocity it has, so if it has been falling for a bit it should continue at the same velocity. You're tracing the position, that should indeed continue to decrease. Try tracing ```body.GetLinearVelocity()``` instead.

B.t.w. You should be using ```bodyInterface.SetMotionType(body.GetID(), type, Jolt.Activate);``` and not the other function.

**Comment by LeXXik** [comment]
Yes, the velocity remains the same:

![image](https://github.com/jrouwe/JoltPhysics.js/assets/5677782/30d022ca-a68e-40b0-a797-b68f153fc72c)

Say, a dev wants to manually control the body position for some period. In Bullet we usually switch the type to kinematic and set the desired position, then switch back to dynamic when needed. What would be the correct way in Jolt? Should I switch to static in this case? Can statics be moved?

**Comment by LeXXik** [comment]
Simply setting angular and linear velocities to zero after switching to kinematic did the trick. Closing this.
