### ISSUE TITLE
`jolt-physics.wasm.js + jolt-physics.wasm.wasm` can't work

### ISSUE THREAD

**Issue by finscn** [jrouwe/JoltPhysics.js#58]
the `jolt-physics.wasm-compat.js` could work.
But when I use  `jolt-physics.wasm.js + jolt-physics.wasm.wasm` , it can't.

<img width="761" alt="image" src="https://github.com/jrouwe/JoltPhysics.js/assets/288367/3d492cc9-0afd-47e5-aba6-7b356385ce1c">

<img width="456" alt="image" src="https://github.com/jrouwe/JoltPhysics.js/assets/288367/4851feae-acd7-4fc5-bfd6-9fafa8e0a203">

**Comment by kutu** [comment]
do you use `Jolt` as variable after initialization of Jolt library?
like
```js
import JoltLib from 'jolt-physics/wasm';

Jolt = (await JoltLib({
  locateFile: function(path) {
    return `wasm/${path}`;
  }
}));

jolt = new Jolt.JoltInterface(settings);
physicsSystem = jolt.GetPhysicsSystem();
bodyInterface = physicsSystem.GetBodyInterface();
```

because I use wasm version and its working for me

**Comment by finscn** [comment]
> do you use `Jolt` as variable after initialization of Jolt library? like
> 
> ```js
> import JoltLib from 'jolt-physics/wasm';
> 
> Jolt = (await JoltLib({
>   locateFile: function(path) {
>     return `wasm/${path}`;
>   }
> }));
> 
> jolt = new Jolt.JoltInterface(settings);
> physicsSystem = jolt.GetPhysicsSystem();
> bodyInterface = physicsSystem.GetBodyInterface();
> ```
> 
> because I use wasm version and its working for me

Yes , I do.
I run `console.log(Jolt)` , it can print the content of Jolt object.
<img width="723" alt="image" src="https://github.com/jrouwe/JoltPhysics.js/assets/288367/0f9065ad-b304-4017-ad9d-096ed5340b27">

**Comment by kutu** [comment]
check network tab, if your webpage even loads .wasm file

**Comment by LeXXik** [comment]
The default layers have been removed in favor of user provided ones, so initialization has been changed. Check out the example:
https://github.com/jrouwe/JoltPhysics.js/blob/47cd1a7f0bf72b6fb6e0f274c672e52d98f15f5e/Examples/js/example.js#L85-L92

**Comment by finscn** [comment]
> The default layers have been removed in favor of user provided ones, so initialization has been changed. Check out the example:
> 
> https://github.com/jrouwe/JoltPhysics.js/blob/47cd1a7f0bf72b6fb6e0f274c672e52d98f15f5e/Examples/js/example.js#L85-L92

Thank you.

**Comment by jrouwe** [comment]
@LeXXik Thanks for spotting that! I didn't realize that that was the issue.

I've added an extra [warning](https://github.com/jrouwe/JoltPhysics.js/commit/7c22d4bff15d3be0da8ca103144b809c6860d943) to  help people in the future.
