### ISSUE TITLE
EShapeSubType Mesh and Heightfield enums overwriting EShapeType Mesh and Heightfield enums

### ISSUE THREAD

**Issue by isaac-mason** [jrouwe/JoltPhysics.js#7]
While making changes for #6, an issue with enums overwriting each other was surfaced.

Because enums are exposed via their member names only, they can very easily collide with other enums! In the event of a collision, the last defined enum wins.

Right now the enum values for `EShapeType` `Mesh` and `Heightfield` are overwritten by the `EShapeSubType` `Mesh` and `Heightfield` members.

Here's an excerpt of the `wasm-compat` bundle:

```js
(function(){function b(){a.MOVING=Hp();a.NON_MOVING=Ip();a.Static=Jp();a.Kinematic=Kp();a.Dynamic=Lp();a.Discrete=Mp();a.LinearCast=Np();a.Activate=Op();a.DontActivate=Pp();a.Convex=Qp();a.Compound=Rp();a.Decorated=Sp();a.Mesh=Tp();a.HeightField=Up();a.Sphere=Vp();a.Box=Wp();a.Capsule=Xp();a.TaperedCapsule=Yp();a.Cylinder=Zp();a.ConvexHull=$p();a.StaticCompound=aq();a.MutableCompound=bq();a.RotatedTranslated=cq();a.Scaled=dq();a.OffsetCenterOfMass=eq();a.Mesh=fq();a.HeightField=gq();a.LocalToBodyCOM=
```

Note that `a.Mesh` and `a.Heightfield` (`a` being the minified name for the module itself) is getting assigned to twice.

A workaround that doesn't require any changes is using the emscripten wrapper functions, which are qualified by the enum name, e.g. `Jolt._emscripten_enum_EShapeType_Mesh()`

Otherwise, we could add some enums to `JoltJS.h` with unique member names, and convert between them and the internal enums.

There's an issue on the emscripten repo for this, but there's not much traction right now for a fix: https://github.com/emscripten-core/emscripten/issues/13243

**Comment by jrouwe** [comment]
I ran into the same issue before with another enum. I didn't realize that there was another conflict present. Back then I renamed a C++ enum to get around the conflict but that's much harder now that the library is used by more people.

```Jolt._emscripten_enum_EShapeType_Mesh()``` is not very nice to use, so I think the best option would be to add some enums to JoltJS.h although I don't really know how that could work. I did a quick test, but the generated C++ wrapper code doesn't like that this new enum is cast to EShapeType. If you know how to do this then please go ahead and send a PR.

**Comment by jrouwe** [comment]
Hello,

I've created a tentative fix for this: https://github.com/jrouwe/JoltPhysics.js/compare/main...bugfix/enum_overlap

This works for normal JS, but I'm not sure if this will work for TS (because we'll be comparing an SubShapeType with an ESubShapeType). @isaac-mason what do you think?

**Comment by isaac-mason** [comment]
LGTM! [webidl-dts-gen](https://github.com/pmndrs/webidl-dts-gen) represents all enums with the type `number`, so there should be no issues here 🙂
