### ISSUE TITLE
Body missing ApplyBuoyancyImpulse

### ISSUE THREAD

**Issue by LeXXik** [jrouwe/JoltPhysics.js#75]
I am adding an `ApplyBuoyancyImpulse` method, and am on the latest `0.11.0`. I can see the method in the IDL in the repository, but the body is missing it at runtime. I checked the example, and I should have the same setup:

![image](https://github.com/jrouwe/JoltPhysics.js/assets/5677782/b8826897-3d82-42ea-ace0-d23008368a7b)

**Comment by LeXXik** [comment]
Nevermind, user error. I was not on the latest build.

**Comment by kutu** [comment]
Do you have the same error with npm
when new jolt version released
you do `npm update`
but then no new version installed

I have to remove package and then install, to get new version
```
npm r jolt-physics
npm i jolt-physics
```

other packages updating fine

**Comment by LeXXik** [comment]
Yeah, I have the same issue. I remove the line `jolt-physics` module line in the package.json, then it adds the latest. Not sure what's up.
