### ISSUE TITLE
Set up github action to build and deploy examples to github pages

### ISSUE THREAD

**Issue by isaac-mason** [jrouwe/JoltPhysics.js#8]
Creating this issue to track configuring a github action to build the library and deploy examples to github pages.
 
https://github.com/jrouwe/JoltPhysics.js/pull/5#issuecomment-1509875790
https://github.com/jrouwe/JoltPhysics.js/pull/5#issuecomment-1509880266

For reference, here's an example github action that installs and uses the emscripten SDK: https://github.com/isaac-mason/recast-navigation-js/blob/main/.github/workflows/release.yml

**Comment by isaac-mason** [comment]
I should get time for this in the coming week 🙂

**Comment by isaac-mason** [comment]
Ah, looks like I lied 😉

This is still on my radar, will see if I get time for it soon.

Otherwise happy to provide guidance to whoever else might want to help with this.

**Comment by jrouwe** [comment]
I'm not in a hurry... 😄

**Comment by jrouwe** [comment]
Examples are now being deployed to gh-pages (note that it just references the latest release on www.unpkg.com instead of building), building the lib and publishing is still todo.

**Comment by isaac-mason** [comment]
I've raised #31 which will build the lib when deploying examples.

As for publishing, there are a few approaches we could take.

Starting simple, we could just run `npm publish` in an action, and create commits bumping the version number in `package.json` to release.

There are also tools like [changesets](https://github.com/changesets/changesets) and `semantic-release` that manage version bumping for you & creation of github releases and tags.

**Comment by jrouwe** [comment]
> Starting simple, we could just run npm publish in an action, and create commits bumping the version number in package.json to release.

Do I understand correctly that this would be a github action that listens to changes on package.json and does build + npm publish whenever this happens? Is so, than that looks sufficient indeed.

changesets also looks nice, although I don't fully understand from the documentation how you interact with it. It looks like you need to add a specific tag to the commit in order to bump a patch/minor or major revision?

**Comment by jrouwe** [comment]
> Yep that's right - we'd likely run an action that checks if the version in package.json is published on npm already, and publishes if not.

Is there an example of this somewhere? (I think simple is good in this case)

**Comment by isaac-mason** [comment]
Simple is good indeed!

We'd just need to run a shell script like this one at the end of the current github action:

```sh
#!/bin/sh

# Read the version from package.json
VERSION=$(node -pe "require('./package.json').version")

# Check if the version has been published on npm
if npm view wandom@$VERSION version &>/dev/null; then
  echo "Version $VERSION is already published on npm, nothing to do."
else
  echo "Version $VERSION has not been published yet, publishing to npm now..."
  npm publish
  echo "Published version $VERSION to npm."
fi
```

We'll also need to set an `NPM_TOKEN` environment variable in the github action: https://docs.npmjs.com/using-private-packages-in-a-ci-cd-workflow#set-the-token-as-an-environment-variable-on-the-cicd-server

**Comment by jrouwe** [comment]
Ok, thanks for the hint! I'll try this out.

**Comment by jrouwe** [comment]
I managed to make it work, thanks for the help!
