### ISSUE TITLE
Uncaught Error: Aborted(OOM). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by geotyper** [jrouwe/JoltPhysics.js#9]
When try to run examples, find that if create:
 let hull = new Jolt.ConvexHullShapeSettings;
or 
let shape_settings = new Jolt.StaticCompoundShapeSettings();
and amount of objects more than preliminary 30 (not set counter)
jolt.js breaks with error Uncaught Error: Aborted(OOM). Build with -sASSERTIONS for more info.

The error come from this code new Jolt.ShapeGetTriangles:
// Optionally create mesh
if (threeObject == null)
threeObject = getThreeMeshForShape(shape, material); 
and when that code try to create triangle data example crashed:
let triContext = new Jolt.ShapeGetTriangles(shape, Jolt.AABox.prototype.sBiggest(), shape.GetCenterOfMass(), Jolt.Quat.prototype.sIdentity(), new Jolt.Vec3(1, 1, 1));

The easy way to repeat this error to set only one mesh type in example, error is always appears.
![Screenshot at 2023-05-04 21-00-32](https://user-images.githubusercontent.com/30755433/236289813-d4ce1210-5f9d-460e-9211-8bbbc1491b2e.png)

and one more as info, not about error:
it can be possible to import jolt.js to project, without edit html
![Screenshot at 2023-05-04 21-01-48](https://user-images.githubusercontent.com/30755433/236290428-0c1bf52a-6b68-404c-995a-3b48e999d9d0.png)

**Comment by geotyper** [comment]
Sorry about: it can be possible to import jolt.js to project, without edit html.
clone sometime ago your git and not update it, now see that it changes also in method of add jolt to project.

**Comment by jrouwe** [comment]
Thanks for the report! I'm not able to test anything right now, I will get back to you next week.

**Comment by jrouwe** [comment]
I managed to track down the problem and submitted a fix in e266858537d0d321662a8056e2380debde1d273b (published to npm as v0.0.5).
